FROM node:20-alpine
RUN apk add --no-cache openssl
WORKDIR /app
COPY package*.json ./
COPY shared/ ./shared/
RUN npm install --workspace=shared
WORKDIR /app/shared
CMD ["npx", "prisma", "migrate", "deploy", "--schema=prisma/schema.prisma"]
